submit final de la encuesta, el alumno completa la encuesta tradicion…
arq1-rizzi-tella-calvento/react-frontend pull request #3
Opened 2017-11-19 19:25 UTC by patriciotella

…al solo con las materias que no aprobo y selecciona las opciones disponibles.

2017-11-19 19:30 UTC, romanrizzi requested changes

2017-11-19 19:30 UTC, romanrizzi commented on src/actions.js
>    }
No es necesario hacer un dispatch con redux

2017-11-19 19:30 UTC, romanrizzi commented on src/components/SubjectsList.jsx
> +    };
Esto no va aca, lo tenemos que hacer mediante el router a esto. Fijate que yo habia creado una URL para la encuesta

2017-11-19 22:26 UTC, patriciotella commented on src/actions.js
>    }
no elimine nada del codigo que estaba, solamente no lo use. Creo que @jcalvento estaba usandolo tambien

2017-11-20 00:24 UTC, jcalvento commented on src/components/SubjectsList.jsx
> +    element.classList.add(classAdd);
2 espacios de identación ftw

2017-11-20 00:24 UTC, jcalvento commented on src/actions.js
>    }
Yo prefiero encapsular las cosas así que empezar a mezclar las cosas que irían en los reducers en los componentes. Igual me parece que cualquiera de las dos formas no es bloqueante

2017-11-20 00:24 UTC, jcalvento commented on src/components/SubjectsList.jsx
> +                        { this.state.subjects.map((name, id) => {
Puede ser una función

2017-11-20 00:24 UTC, jcalvento commented on src/components/SubjectsPoll.jsx
> +                        { this.state.subjects.map(subject => {
Puede ser una función también

2017-11-20 00:24 UTC, jcalvento commented on src/components/SubjectsPoll.jsx
> +            var subjectCast = { id: subject[1], name: subject[0], condition: ''}
Estos son los subjects que vienen del back? Para qué es necesario castearlos así? No se puede usar el JSON como viene con las propiedades?

2017-11-20 18:16 UTC, patriciotella commented on src/components/SubjectsList.jsx
> +    element.classList.add(classAdd);
autoidentacion

2017-11-20 18:17 UTC, patriciotella commented on src/components/SubjectsList.jsx
> +                        { this.state.subjects.map((name, id) => {
ya esta asi en master pero lo extraigo

2017-11-20 18:17 UTC, patriciotella commented on src/components/SubjectsPoll.jsx
> +                        { this.state.subjects.map(subject => {
lo extraigo x2

2017-11-20 18:18 UTC, patriciotella commented on src/components/SubjectsPoll.jsx
> +            var subjectCast = { id: subject[1], name: subject[0], condition: ''}
estas eran las materias aprobadas no estaba el endpoint para las encuesta, ahora ya se pueden obtener con el commit de @romanrizzi

2017-11-20 20:38 UTC, romanrizzi commented on src/actions.js
>    }
Preferible extraerlo fuera del componente como una función común en mi opinion.

2017-11-20 20:46 UTC, romanrizzi requested changes

2017-11-20 20:46 UTC, romanrizzi commented on src/actions/auth.js
> +};
Esto no va en este archivo, no esta relacionado con auth

2017-11-20 20:46 UTC, romanrizzi commented on src/actions.js
>    }
No se si quedo colgado esto

2017-11-20 20:46 UTC, romanrizzi commented on src/actions/subjects.js
> +const nonApproveSubjects = (userId, success, error) => {
No seria mejor llamarlo `surveyOptions`?

2017-11-20 20:46 UTC, romanrizzi commented on src/components/SubjectsPoll.jsx
> +        const userId = this.props.location.pathname.split('/');
Fijate esto: https://stackoverflow.com/a/45599016

2017-11-20 20:46 UTC, romanrizzi commented on src/components/SubjectsPoll.jsx
> +    }
La forma de accerde al userId es mas facíl usando la api del router (fijate lo que puse arriba)

2017-11-20 20:46 UTC, romanrizzi commented on src/components/SubjectsPoll.jsx
> +    }
Esto no hace falta ya que las fat arrow functions (=>) ya bindean el contexto. No hace falta escribir el constructor

2017-11-20 20:49 UTC, patriciotella commented on src/actions.js
>    }
jajaja, yo dije que no lo estaba usando, pero pense que juli si, por eso no elimine la clase

2017-11-20 20:51 UTC, patriciotella commented on src/components/SubjectsPoll.jsx
> +        const userId = this.props.location.pathname.split('/');
evalue lo que me venia en las props, habia hecho algo como eso al principio, pero no lo tenia :(

2017-11-20 21:17 UTC, romanrizzi approved these changes

2017-11-20 21:46 UTC, merged